-- Adiciona uma coluna 'code' auto-incrementável
ALTER TABLE public.properties 
ADD COLUMN code BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- Cria um índice único para garantir que o código seja exclusivo e rápido de buscar
CREATE UNIQUE INDEX properties_code_idx ON public.properties (code);
